server:
  ip: localhost
  port: 10086
rules:
  - path:
      backend:
        prefix: /test1
        url: localhost:8899 # 真正要访问的服务
  - path:
      backend:
        prefix: /aaaa
        url: 172.20.10.4:12308 # 真正要访问的服务
  - path:
      backend:
        prefix: /bbbb
        url: localhost:8888 # 真正要访问的服务
  - path:
      backend:
        prefix: /test2
        url: 172.20.10.4:8000 # 真正要访问的服务