Rules:
- Path:
    Backend:
      Prefix: /test1
      Url: http://localhost:8899
- Path:
    Backend:
      Prefix: /tttt
      Url: https://github.com
- Path:
    Backend:
      Prefix: /aaaa
      Url: http://localhost:8081
Server:
  Ip: localhost
  Params: name,user,aaaa
  Port: 10086
