apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproxy-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: myproxy-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: myproxy-controller
    spec:
      nodeName: vm-0-16-centos # 只调度到这个节点上
      serviceAccountName: myproxy-sa # 配置service account
      containers:
        - name: myproxy
          image: myproxyoperator:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: "Release"
              value: "1"
          workingDir: "/app"
          command: ["./myproxyoperator"]
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myproxy-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 10086
      nodePort: 31186
  selector:
    app: myproxy-controller