apiVersion: api.practice.com/v1alpha1
kind: Proxy
metadata:
  name: myproxy
spec:
  server:                               # 反向代理 server ip:port
    ip: localhost
    port: 10086
  rules:                                # 后端路由列表
    - path:
        backend:                        # 后端
          prefix: /service1             # 自定义前缀
          url: http://localhost:8899    # 真正要访问的服务
    - path:
        backend:
          prefix: /service2
          url: http://localhost:8800