apiVersion: api.practice.com/v1alpha1
kind: Proxy
metadata:
  name: myproxy
spec:
  server:
    ip: localhost
    port: 10086
  rules:
    - path:
        backend:
          prefix: /test1
          url: http://localhost:8899 # 真正要访问的服务
    - path:
        backend:
          prefix: /aaaa
          url: http://172.20.10.4:12308 # 真正要访问的服务
    - path:
        backend:
          prefix: /bbbb
          url: http://localhost:8888 # 真正要访问的服务
    - path:
        backend:
          prefix: /test2
          url: http://172.20.10.4:8000 # 真正要访问的服务